### ISSUE TITLE
Some review comments

### ISSUE THREAD

**Issue by corneliusweig** [ahmetb/krew-index-autoapprove#1]
I had a short look at your tool. Without a PR I cannot add comments to the source, so I'll do that manually here:

- I think we want `if len(vOld) == 2 || len(vNew) == 2 {` here https://github.com/ahmetb/krew-index-autoapprove/blob/d4fefd2b73ab383e0b8de072b164b777299d1a56/bump/bump.go#L154
  - same here https://github.com/ahmetb/krew-index-autoapprove/blob/d4fefd2b73ab383e0b8de072b164b777299d1a56/bump/bump.go#L170
- The tool does not yet check if the shaSum has changed.
- The tool would approve syntactically illegal yaml files, for example
   ```yaml
   platforms:
     - uri: https://example.com/my.tar.gz
       sha256: 123
   ```
   to (mind the missing `-`)
   ```yaml
   platforms:
       uri: https://example.com/my.tar.gz
       sha256: 123
   ```
- The tool does not recognize, if the version is also part of the executable (see  `curl -H "Accept: application/vnd.github.v3.diff" https://api.github.com/repos/kubernetes-sigs/krew-index/pulls/230`)
- I think you can resolve your todo item about added plugins, because the filename will differ in that case (see ` curl -H "Accept: application/vnd.github.v3.diff" https://api.github.com/repos/kubernetes-sigs/krew-index/pulls/173`). This will be caught by https://github.com/ahmetb/krew-index-autoapprove/blob/d4fefd2b73ab383e0b8de072b164b777299d1a56/bump/bump.go#L24

All of these errors would be caught by our CI tests though, so they don't need to be fixed.

All in all this looks really promising. Very nice idea and neat execution! I'm curious to see this in action now!
